name: "Test Merge Requests"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'target/**'
      - 'test/**'
      - '.dockerignore'
      - '.gitmodules'
      - 'Dockerfile'
      - 'setup.sh'

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build images locally
        uses: docker/build-push-action@v2.10.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            VCS_VER=${{ github.ref }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: mailserver-testing:ci
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build image for test suit
        uses: docker/build-push-action@v2.10.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            VCS_VER=${{ github.ref }}
          platforms: linux/amd64
          load: true
          tags: mailserver-testing:ci
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Run test suite
        run: >
          NAME=mailserver-testing:ci
          bash -c 'make generate-accounts tests'
        env:
          CI: true
